version: '3'

services:
  web:
    build: .
    command: gunicorn superfamilytree.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=www.superfamilytree.com,185.166.39.206
      - DATABASE_URL=sqlite:///db.sqlite3 
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html/Super-Family-Tree/superfamilytree/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./media:/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
