version: '3'

services:
  web:
    build: .
    command: gunicorn superfamilytree.wsgi:application --bind 0.0.0.0:80 --workers 3 --timeout 120
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=www.superfamilytree.com,185.166.39.206
      - DATABASE_URL=sqlite:///db.sqlite3 
    networks:
      - app-network

networks:
  app-network:
