# Generated by Django 5.0.8 on 2024-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
